version: "2"

run:
  concurrency: 4
  timeout: 5m
  tests: true

linters:
  default: none
  enable:
    - bodyclose
    - copyloopvar
    - errcheck
    - gocritic
    - gocyclo
    - govet
    - ineffassign
    - misspell
    - nolintlint
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    gocyclo:
      min-complexity: 20
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gocyclo
          - unparam
        path: _test\.go
    paths:
      - vendor
      - third_party$
      - builtin$
      - examples$

formatters:
  enable:
    - gci
    - gofmt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/m-amaresh/fgm)
  exclusions:
    generated: lax
    paths:
      - vendor
      - third_party$
      - builtin$
      - examples$
